//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizzashop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Cusid { get; set; }
        public string CusFirstName { get; set; }
        public string CusLastName { get; set; }
        public int CusPhoneNum { get; set; }
        public string CusAddress { get; set; }
        public string CusOrder { get; set; }
        public int FoodId { get; set; }
    
        public virtual CustFood CustFood { get; set; }
        public virtual CustFood CustFood1 { get; set; }
    }
}
